
version: "3"
services:
  postgres:
    image: postgres:10.6-alpine
    hostname: library-db
    container_name: library-db
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: facundo
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
